services:
  - type: web
    name: lumina-academic-assistant
    env: node
    plan: free
    buildCommand: npm install && npm run build && node deploy/post-build.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    domains:
      - luminaassist.onrender.com
