services:
  - type: web
    name: lumina-academic-assistant
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: AIzaSyAUjbQLPVAyFZHz5s7L1inT-oTSbcSeM9w
        sync: false
    healthCheckPath: /
    autoDeploy: true
    domains:
      - luminaassist.onrender.com
