services:
  - type: web
    name: lumina-academic-assistant
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    domains:
      - lumina-assistant.onrender.com